### ISSUE TITLE
Add a "Table of content generated using [this app](https://tableofcontents.herokuapp.com/)" line

### ISSUE THREAD

**Issue by vvasuki** [raychenon/auto-toc#1]
Add a "Table of content generated using [this app](https://tableofcontents.herokuapp.com/)" line in the output. It will same much effort...

**Comment by raychenon** [comment]
Done. https://tableofcontents.herokuapp.com/ is updated.

This issue raises a good question: whether the web app should be part of this project ?
For now, the Play app source code is not in a clean state. 
I will publish it on github under this project or another name.

**Comment by vvasuki** [comment]
App seems to be broken:

Application error
An error occurred in the application and your page could not be served. If you are the application owner, check your logs for details.

**Comment by raychenon** [comment]
Hi Vishvas,
the old application is on
https://testtableofcontents.herokuapp.com . It is still running

I swapped the name of the of the old and new applications.
For weird reasons, I cannot re swap their names.

**Comment by vvasuki** [comment]
Ah thanks!

Generated using this app line is not copy pasteable markdown though -
![image](https://cloud.githubusercontent.com/assets/2664797/26437978/189e0680-40d5-11e7-9941-9827b7ee185e.png)

**Comment by raychenon** [comment]
I'm on the road now. I will check this afternoon.

**Comment by raychenon** [comment]
On **Chrome**, I can copy paste what is under "Table of content generated using this app". 
Can you tell me the steps how to reproduce the "not copy pasteable markdown"bug ?
![screen shot 2017-05-25 at 10 54 11 pm](https://cloud.githubusercontent.com/assets/3137141/26470225/31e0c010-419d-11e7-9a0d-946b9327f0a1.png)


https://tableofcontents.herokuapp.com/ is back.  There was a problem in the .conf files.
I will publish the new Play app on github this weekend.

**Comment by vvasuki** [comment]
I want to copy paste "generated using this app" bit into my md file too.. That is the bug..

**Comment by raychenon** [comment]
Ah ok, you want to copy this text and its url .
That's a good ad for this project :)

**Comment by raychenon** [comment]
Ok, I pushed the changes. 
The text you copy paste a text is :
`[Table of contents generated using this app](https://tableofcontents.herokuapp.com)`
